Repository puppetlabs/puppet_litmus, pull requests merged in 2019-06, with the labels that each got.

#126 (FM-7721) add unit tests for the major parts
  .gitignore
  Gemfile
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
  spec/lib/puppet_litmus/version_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#124 Addition of pe_install rake task
  lib/puppet_litmus/rake_tasks.rb
Labels: feature

#122 FM-8119 - provision_from_metadata should be deprecated
  lib/puppet_litmus/rake_tasks.rb
Labels: maintenance

#128 (feat) add provision_and_install task
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: feature

#127 (FM-7963) Add yardoc comments to inventory_manipulation and rake_task…
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_tasks.rb
  lib/puppet_litmus/serverspec.rb
Labels: feature

#137 (FM-8178) Make params passable using provision.yaml
  lib/puppet_litmus/rake_tasks.rb
Labels: feature

#138 WIP FM-8269 add or remove features in inventory file
  lib/puppet_litmus/inventory_manipulation.rb
  spec/data/inventory.yaml
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
Labels: feature

#136 (FM-8268) adding file/directory upload method
  lib/puppet_litmus/serverspec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: feature

#139 (FM-8273) Enable parallel acceptance from Windows
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#140 (minor fix for addfeaturegroup function)
  lib/puppet_litmus/inventory_manipulation.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
Labels: bugfix

#142 (maint) release_prep_0.6.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#145 (FM-8284) Add bolt_run_script command
  lib/puppet_litmus/serverspec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: feature

#146 FM-8286 run_bolt_task returns bolt result object
  lib/puppet_litmus/serverspec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: feature

#148 (FM-8288) Release prep 0.7.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#149 (FM-8299) spinner runs after spec_prep in provision
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix
