Repository puppetlabs/puppet_litmus, pull requests merged in 2019-11, with the labels that each got.

#213 Invoke spec_prep before provision_list
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#209 (FM-8611) Reinstall module
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
Labels: feature

#215 (maint) Lazily load gems in rake tasks
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
Labels: maintenance

#216 (maint) declare PuppetLitmus module
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#218 Use git in module Gemfile
  .travis.yml
Labels: maintenance
