Repository puppetlabs/puppet_litmus, pull requests merged in 2019-05, with the labels that each got.

#101 (FM-7978) use a spinner for parallel acceptance
  lib/puppet_litmus/rake_tasks.rb
  puppet_litmus.gemspec
Labels: feature

#108 (FM-8073) Support blocks in apply_manifest
  lib/puppet_litmus/rake_tasks.rb
  lib/puppet_litmus/serverspec.rb
Labels: bugfix, feature

#92 (FM-7718) Support vagrant provisioning
  lib/puppet_litmus/rake_tasks.rb
Labels: feature

#109 (maint) release prep 0.2.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#112 (FM-8094) remove workaround for bolt on windows
  lib/puppet_litmus/serverspec.rb
Labels: bugfix

#115 (FM-8105) when in CI correctly display test summary
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#111 (bugfix) handle block in bolt_task
  lib/puppet_litmus/serverspec.rb
Labels: bugfix

#116 (maint) 0.3.0 release prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#117 (bugfix) fix result object for bolt task
  lib/puppet_litmus/serverspec.rb
Labels: bugfix

#119 (FM-8072) add noop flag detection to apply_manifest
  lib/puppet_litmus/serverspec.rb
Labels: feature

#120 (bugfix) raise on task failure
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#121 (maint) release prep 0.4.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance
