Repository puppetlabs/puppet_litmus, pull requests merged in 2019-09, with the labels that each got.

#177 (FM-8486) Remove tty-spinner when running in CI
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#178 0.9.1 release prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#179 (FM-8342) Handle mocking of localhost
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_tasks.rb
  lib/puppet_litmus/serverspec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: bugfix, feature

#182 (FM-8494) fix provision progress in travis and rubocop
  .rubocop.yml
  lib/puppet_litmus/rake_tasks.rb
  lib/puppet_litmus/serverspec.rb
Labels: bugfix

#180 (bugfix) Report both stderr and stdout when an error is detected
  lib/puppet_litmus/serverspec.rb
Labels: bugfix

#187 (maint) adding code coverage to travis
  .travis.yml
  Gemfile
  spec/spec_helper.rb
Labels: maintenance

#189 (maint) adding codeowners file
  CODEOWNERS
Labels: maintenance

#185 (FM-8513) Better handling of errors and changes
  lib/puppet_litmus/serverspec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: feature

#184 (FM-8456) set inventory vars when provisioning
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
Labels: backwards-incompatible, feature

#191 0.10.0 release prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance
