Repository puppetlabs/puppet_litmus, pull requests merged in 2019-07, with the labels that each got.

#152 (minor update) fix multiple update to inventoryfile
  lib/puppet_litmus/inventory_manipulation.rb
Labels: maintenance

#151 (MAINT) Release prep 0.7.1
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#153 (bugfix) bolt_task populates stdout, if successful
  lib/puppet_litmus/serverspec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: bugfix

#154 (maint) 0.7.2 release prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#155 (FM-8303) Ensure run_bolt_task works against localhost
  lib/puppet_litmus/serverspec.rb
Labels: bugfix

#156 (bugfix) Use quote around upload path
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#157 (maint) release prep 0.7.3
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#159 (feat) Add support to show apply_manifest output for debugging
  lib/puppet_litmus/serverspec.rb
Labels: feature
