Repository puppetlabs/puppet_litmus, pull requests merged in 2019-10, with the labels that each got.

#192 (FM-7077) add install_modules_from_directory
  lib/puppet_litmus/rake_tasks.rb
  spec/data/doot.tar.gz
  spec/lib/puppet_litmus/rake_tasks_spec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
Labels: feature

#195 (bugfix) error on provisionlist with no key
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: bugfix

#196 (FM-8464) Remove bolt version pin
  puppet_litmus.gemspec
Labels: bugfix

#197 (FM-8570) 0.11.0 release prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#198 (FM-8346) Create inventory group if missing when adding a node
  lib/puppet_litmus/inventory_manipulation.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
Labels: bugfix

#199 (maint) fix codecoverage
  .rubocop.yml
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
  spec/lib/puppet_litmus/serverspec_spec.rb
  spec/lib/puppet_litmus/version_spec.rb
Labels: maintenance

#200 (FM-8316) Rename serverspec to puppet helpers
  lib/puppet_litmus.rb
  lib/puppet_litmus/puppet_helpers.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
Labels: maintenance

#201 (bugfix) pin pdk gem and require tty
  lib/puppet_litmus/rake_tasks.rb
  puppet_litmus.gemspec
Labels: bugfix

#203 (MODULES-9998) Require pdk/util and remove pdk pin
  lib/puppet_litmus/rake_tasks.rb
  puppet_litmus.gemspec
Labels: maintenance

#204 0.11.2 release prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#194 (feature) run_bolt_task allows a custom inventory file
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/puppet_helpers.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/data/jim.yaml
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
Labels: feature

#208 (FM-8312) Move ruby code in rake tasks to a helper class
  lib/puppet_litmus.rb
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
Labels: maintenance

#207 (MODULES-10019) Add exit_status to run_shell
  lib/puppet_litmus/puppet_helpers.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
Labels: bugfix

#210 (FM-8355) Add spec_helper_acceptance
  lib/puppet_litmus.rb
  lib/puppet_litmus/spec_helper_acceptance.rb
Labels: feature
