Repository puppetlabs/puppet_litmus, pull requests merged in 2020-11, with the labels that each got.

#328 Add provision_service to the list of supported provision tasks
  lib/puppet_litmus/rake_helper.rb
Labels: maintenance

#330 simplify GCP images to use family names
  exe/matrix_from_metadata
Labels: bugfix

#335 Use default windows-2016 server image
  exe/matrix_from_metadata
Labels: bug

#336 (GH-326) - Return node name when testing is complete
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#341 Show successful agent result when DEBUG env true
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#343 Revert "Use puppet 7 collection in acceptance test matrix"
  exe/matrix_from_metadata
Labels: maintenance

#342 (IAC-1258) 0.19.0 Release Prep
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#345 Check connectivity after provision
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  puppet_litmus.gemspec
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: feature

#346 (maint) set debug to print config results
  lib/puppet_litmus/rake_tasks.rb
Labels: maintenance

#347 Remove debugging output
  lib/puppet_litmus/rake_helper.rb
Labels: bug, bugfix

#348 Release prep for v0.20.0
  .travis.yml
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#344 Fix append_cli parameters
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix
