Repository puppetlabs/puppet_litmus, pull requests merged in 2020-01, with the labels that each got.

#228 Improve error reporting
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#230 (feat) new rake task to check nodes are available
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: feature

#232 (maint) release prep 0.14.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#206 (MAINT) Ensure acceptance:localhost task also runs spec_prep
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: feature

#237 Cleanup .travis.yml
  .travis.yml
Labels: maintenance
