Repository puppetlabs/puppet_litmus, pull requests merged in 2020-02, with the labels that each got.

#233 (feat) move to v2 of bolt inventory file
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_helper.rb
  spec/data/inventory.yaml
  spec/data/jim.yaml
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: backwards-incompatible, feature

#238 (MODULES-10478) honeycomb integration to litmus
  Gemfile
  lib/puppet_litmus.rb
  lib/puppet_litmus/puppet_helpers.rb
  puppet_litmus.gemspec
Labels: feature

#239 (MODULES-10479) Release prep 0.15.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#240 (maint) Release prep 0.15.0
  CHANGELOG.md
Labels: maintenance

#243 (IAC-536) Unify field names; fallback for branch builds
  .travis.yml
  lib/puppet_litmus.rb
Labels: feature

#248 (GH-246) Fix install_modules_from_directory logic
  .rubocop.yml
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#244 (MAINT) Add interpolate_powershell helper method
  lib/puppet_litmus/util.rb
  spec/lib/puppet_litmus/util_spec.rb
Labels: feature

#251 Make InventoryManipulation available to all rake tasks
  .rubocop.yml
  Gemfile
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
Labels: bugfix
