Repository puppetlabs/puppet_litmus, pull requests merged in 2020-03, with the labels that each got.

#258 (IAC-550) Add Appveyor testing
  appveyor.yml
Labels: maintenance

#235 (GH-234) Remove PDK dependency
  Gemfile
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  puppet_litmus.gemspec
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
  spec/lib/puppet_litmus/version_spec.rb
  spec/spec_helper.rb
Labels: bugfix

#263 (maint) release prep 0.16.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#262 Open Litmus to use custom provisioners
  lib/puppet_litmus/rake_helper.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
Labels: feature

#264 (IAC-537) capture more info for honeycomb
  lib/puppet_litmus.rb
  lib/puppet_litmus/puppet_helpers.rb
  lib/puppet_litmus/rake_helper.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
Labels: feature

#268 (maint) make sure that errors in the acceptance tests fail; fix code to actually pass
  appveyor.yml
  lib/puppet_litmus/inventory_manipulation.rb
Labels: maintenance

#267 (maint) release prep 0.17.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#272 (IAC-658) suppress libhoney warning
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#271 (IAC-660) make the platform fact optional
  lib/puppet_litmus.rb
  lib/puppet_litmus/honeycomb_utils.rb
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/puppet_helpers.rb
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#260 Allow users to install modules form a private forge repository
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
Labels: feature

#247 Improve rake task install_module and install_modules_from_directory
  .travis.yml
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: bugfix

#274 Add `--trace` by default to all `puppet apply` commands
  lib/puppet_litmus/puppet_helpers.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
Labels: bugfix

#275 (IAC-187) force installing modules
  .travis.yml
  lib/puppet_litmus/rake_helper.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: bugfix

#273 Fix missing require in `litmus:tear_down`
  .travis.yml
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#254 (feat) move to using bolt v2
  lib/puppet_litmus/puppet_helpers.rb
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  puppet_litmus.gemspec
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
  spec/lib/puppet_litmus/rake_helper_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: feature

#279 Use 'target' instead of 'node' in bolt result hashes
  lib/puppet_litmus/rake_tasks.rb
  spec/lib/puppet_litmus/puppet_helpers_spec.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: bugfix

#277 (maint) release prep for 0.18.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance
