Repository puppetlabs/puppet_litmus, pull requests merged in 2021-01, with the labels that each got.

#364 David's rspec fault fix
  .travis.yml
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: maintenance

#366 (IAC-1287) - Only log errors in debug mode
  lib/puppet_litmus/rake_tasks.rb
Labels: maintenance

#367 (IAC-1287) Only log transient provisioning errors in debug mode
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix

#368 (maint) improve readability of agent install task
  lib/puppet_litmus/rake_tasks.rb
Labels: maintenance

#369 (maint) better UX for connectivity check task
  lib/puppet_litmus/rake_helper.rb
Labels: maintenance

#370 (IAC-1369) Release Prep 0.21.0
  .travis.yml
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#373 Use puppet 6 nightlies and increase timeout limit
  exe/matrix_from_metadata
  lib/puppet_litmus/rake_helper.rb
Labels: feature

#371 (IAC-1365) - Workaround bolt/windows/exitcode bug
  lib/puppet_litmus/puppet_helpers.rb
Labels: bugfix

#374 (IAC-1396) v0.22.0 Release
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#352 Remove rhel6 from all tests
  exe/matrix_from_metadata
Labels: feature
