Repository puppetlabs/puppet_litmus, pull requests merged in 2021-09, with the labels that each got.

#428 add more tests for matrix_from_metadata_v2
  spec/exe/fake_metadata.json
  spec/exe/matrix_from_metadata_v2_spec.rb
Labels: maintenance

#429 Release Prep v0.29.0
  CHANGELOG.md
  Gemfile
  lib/puppet_litmus/version.rb
Labels: maintenance

#431 (IAC-1751/IAC-1752) Add support for Rocky and AlmaLinux 8 to `extract_matrix_from_metadate_v2`
  exe/matrix_from_metadata_v2
Labels: feature

#432 (IAC-1751) Fix for Rocky 8
  exe/matrix_from_metadata_v2
Labels: bugfix

#433 Release prep v0.30.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance
