Repository puppetlabs/puppet_litmus, pull requests merged in 2021-02, with the labels that each got.

#379 Isolate puppet_helpers workaround for windows os family
  lib/puppet_litmus/puppet_helpers.rb
Labels: bugfix

#381 Release prep v0.23.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#383 Ensure that first-order failures in idempotent_apply get reported
  lib/puppet_litmus/puppet_helpers.rb
Labels: bug

#384 release prep v0.23.1
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#386 Remove puppet5 from matrix_from_metadata script and update puppet6 and puppet7 versions
  exe/matrix_from_metadata
Labels: feature

#387 Release prep 0.24.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#389 (IAC-1442) - Removal of Inappropriate Terminology
  lib/puppet_litmus/puppet_helpers.rb
  spec/lib/puppet_litmus/rake_tasks_spec.rb
Labels: maintenance

#390 (maint) Release prep 0.25.0
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance

#391 Disable testing on docker containers for Debian 8 and Ubuntu 14.04
  exe/matrix_from_metadata_v2
Labels: bugfix

#392 Release prep v0.25.1
  CHANGELOG.md
  lib/puppet_litmus/version.rb
Labels: maintenance
