Repository puppetlabs/puppet_litmus, pull requests merged in 2023-04, with the labels that each got.

#485 (CONT-806) Add Ruby 3.2 support
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  exe/matrix_from_metadata
  exe/matrix_from_metadata_v2
  lib/puppet_litmus/inventory_manipulation.rb
  lib/puppet_litmus/puppet_helpers.rb
  lib/puppet_litmus/rake_helper.rb
  lib/puppet_litmus/rake_tasks.rb
  lib/puppet_litmus/spec_helper_acceptance.rb
  lib/puppet_litmus/version.rb
  spec/lib/puppet_litmus/inventory_manipulation_spec.rb
  spec/lib/puppet_litmus/puppet_litmus_version_spec.rb
Labels: enhancement

#490 (CONT-806) Mapping RC dependencies
  Gemfile
  Rakefile
  puppet_litmus.gemspec
Labels: maintenance

#496 (MAINT) Force newer Puppet 7 Gem
  exe/matrix_from_metadata_v2
  spec/exe/matrix_from_metadata_v2_spec.rb
Labels: bug
