Repository puppetlabs/puppet_litmus, pull requests merged in 2023-07, with the labels that each got.

#506 (FEAT) - Add ability to supply a custom matrix and override default provisioner
  exe/matrix_from_metadata_v2
  lib/puppet_litmus/rake_helper.rb
  spec/exe/matrix_from_metadata_v2_spec.rb
Labels: feature

#508 (CONT-1200) - Add readme section for custom-matrix flag
  README.md
Labels: maintenance

#509 (maint) - fix readme typo
  README.md
Labels: maintenance

#510 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#512 (CONT-1243) - Skip tear_down if no provisioner found
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#513 (maint) - README updates
  README.md
Labels: maintenance

#514 (CAT-1249) - Fix Spinner on Windows Hosts
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix

#516 (CAT-1241) - Adding retry when provision failed with Timeout
  .rubocop_todo.yml
  lib/puppet_litmus/rake_tasks.rb
Labels: bugfix, WIP

#518 (CAT-1265) - Fix agent install on vagrant boxes
  lib/puppet_litmus/rake_helper.rb
Labels: bugfix
