Repository puppetlabs/puppet_litmus, pull requests merged in 2024-05, with the labels that each got.

#551 add supported docker el9 platforms to matrix
  exe/matrix_from_metadata_v2
Labels: enhancement

#560 add amazonlinux litmus images to matrix
  exe/matrix_from_metadata_v2
  spec/exe/fake_metadata.json
  spec/exe/matrix_from_metadata_v2_spec.rb
Labels: enhancement

#559 use dockercli specinfra backend for docker_nodes
  lib/puppet_litmus/spec_helper_acceptance.rb
Labels: bugfix, experimental

#564 (IT-87329) - Update workflows to run on pull_request
  .github/workflows/ci.yml
  .github/workflows/mend.yml
Labels: maintenance
