Repository puppetlabs/puppet_litmus, pull requests merged in 2025-08, with the labels that each got.

#597 (CAT-2416) Address almalinux 8 provisioning issues
  exe/matrix.json
Labels: maintenance

#596 (CAT-2433) Adds option to return latest agent build
  README.md
  exe/matrix_from_metadata_v3
  spec/exe/matrix_from_metadata_v3_spec.rb
Labels: feature

#602 (MAINT) Fix Rocky typo in matrix.json
  exe/matrix.json
Labels: bugfix
